version: '3.9'

services:
  php:
    build:
      context: ..
      dockerfile: Dockerfile.prod.php
    volumes:
      - ../my_symfony_project:/var/www/html

  webserver:
    image: nginx:1.25.3
    volumes:
      - ../config/nginx:/etc/nginx/conf.d
      - ../my_symfony_project:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
